from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Any


def pct(value: float | int | None) -> str:
    if value is None:
        return "n/a"
    return f"{float(value) * 100:.1f}%"


def render_weekly_report(state: dict[str, Any], report_date: date | None = None) -> str:
    report_date = report_date or date.today()
    regime = state.get("regime", {})
    probabilities = regime.get("probabilities", {})
    lines = [
        f"# Macro Regime Weekly - {report_date.isoformat()}",
        "",
        "## Regime",
        "",
        f"- Dominant: **{regime.get('dominant_label', 'unknown')}**",
        f"- Act 1 stagflation: {pct(probabilities.get('act_1_1970s_stagflation'))}",
        f"- Act 2 bond vigilantes: {pct(probabilities.get('act_2_1994_bond_vigilantes'))}",
        f"- Act 3 financial repression: {pct(probabilities.get('act_3_financial_repression'))}",
        f"- Reasoning: {state.get('regime_reasoning', '')}",
        f"- Act 2 note: {state.get('act2_note', '')}",
        "",
        "## Indicators",
        "",
        "| Indicator | FRED | Value | Status | Date |",
        "|---|---:|---:|---:|---:|",
    ]
    for name, item in state.get("indicators", {}).items():
        lines.append(
            f"| {name} | {item.get('series_id', '')} | {item.get('display', '')} | "
            f"{item.get('status', '')} | {item.get('fred_date', '')} |"
        )

    changes = state.get("what_changed") or []
    lines.extend(["", "## What Changed", ""])
    if changes:
        for item in changes:
            lines.append(f"- {item['indicator']}: {item['from']} -> {item['to']} ({item['value']})")
    else:
        lines.append("- No indicator status changes.")

    transmission = state.get("portfolio_transmission", {})
    lines.extend(["", "## Portfolio Transmission", ""])
    if transmission.get("available"):
        lines.append(f"- BTC +1% delta: {transmission.get('btc_plus_1pct_usd')}")
        lines.append(f"- Dominant regime hint: {transmission.get('dominant_regime_hint')}")
        lines.append(f"- Real-yield line: {transmission.get('real_yield_break_2_7_hint')}")
        high_beta = transmission.get("high_beta_assets") or []
        if high_beta:
            lines.extend(["", "| Asset | Beta | Exposure USD | BTC +1% contribution |", "|---|---:|---:|---:|"])
            for item in high_beta:
                lines.append(
                    f"| {item['factor']} | {item['beta_to_btc']:.2f} | "
                    f"{item['exposure_usd']:,.0f} | {item['btc_plus_1pct_contribution_usd']:,.0f} |"
                )
    else:
        lines.append(f"- Skipped: {transmission.get('reason', 'portfolio risk state unavailable')}")

    lines.extend(
        [
            "",
            "## Next Checks",
            "",
            "- Check Treasury auction stress and cross-asset selloff signals externally before interpreting Act 2.",
            "- Treat stale indicators as stale; do not invent missing values.",
            "- Review high-beta exposure if 30Y real yield crosses 2.7%.",
            "",
            "_Generated by macro-regime-kit. Not investment advice._",
            "",
        ]
    )
    return "\n".join(lines)


def write_weekly_report(state: dict[str, Any], reports_dir: Path, report_date: date | None = None) -> Path:
    report_date = report_date or date.today()
    target_dir = reports_dir / "macro_weekly_reports"
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / f"{report_date.isoformat()}.md"
    target.write_text(render_weekly_report(state, report_date))
    return target

